twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_horizontal_layout.html.twig'
        - '@TetranzSelect2Entity/Form/fields.html.twig'
    globals:
        date_format: '%app.date_format%'
        category_repository: '@App\Repository\CategoryRepository'
